"""paper book and trade columns

Revision ID: 9c374298c567
Revises: 5d21d77e5adf
Create Date: 2026-09-17 15:42:38.145265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c374298c567'
down_revision: Union[str, None] = '5d21d77e5adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_books',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('paper_trades', sa.Column('client_trade_id', sa.String(length=64), nullable=True))
    # server_default so the NOT NULL columns can be added to a table that
    # already has rows; the ORM supplies its own value on insert.
    op.add_column('paper_trades', sa.Column('product', sa.String(length=8), nullable=False, server_default='MIS'))
    op.add_column('paper_trades', sa.Column('charges', sa.Float(), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_paper_trades_user_client_id', 'paper_trades', ['user_id', 'client_trade_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_paper_trades_user_client_id', 'paper_trades', type_='unique')
    op.drop_column('paper_trades', 'charges')
    op.drop_column('paper_trades', 'product')
    op.drop_column('paper_trades', 'client_trade_id')
    op.drop_table('paper_books')
    # ### end Alembic commands ###
